### ISSUE TITLE
Postman Collection shall provide Response Examples

### ISSUE THREAD

**Issue by SebastianOpriel** [sovity/edc-ce#1068]
The response fields are not set. Thus, users don't know what to expect as a response from the API. Example: https://github.com/sovity/edc-ce/blob/83e201216362b9398bbea0ef98172d217c2d94fc/docs/api/postman_collection.json#L53

**Comment by tmberthold** [comment]
Hello and thank you for the hint.
However, this should be part of the OpenAPI specifications and not of the Postman Collection.
E.g. here: https://edc-ce.docs.sovity.de/backend/what-is-the-api-wrapper/openapi-specification/assets

**Comment by SebastianOpriel** [comment]
If I import postman collection, I usually have a sample body etc. but in this case no sample as output. The postman collection could be enhanced with this. I suggest: work through all default API calls (with preset dummy values) and use output as dummy response

**Comment by tmberthold** [comment]
Thanks for sharing these insights, as I said, this should be part of the OpenAI standard specification.
Accordingly, this is closed as not planned.
