### ISSUE TITLE
EDC API Wrapper: Code Splitting

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-ce#188]
# Feature
# Description
Currently our EDC API Wrapper splits its APIs by Java Packages allowing us to implement the required components in just three packages.

Previous concerns were raised whether that is sufficiently aesthetic.

The idea is to explore how feasible it is to further separate code into individual packages to realize separate deployment units or even provide a framework (?) for automatically building the API Wrapper from components.

The general goal might be to provide parts of the API without others or even collect the API endpoints via class path allowing us to add private endpoints in our closed source variants without having to interact with the edc-extensions part.

**Comment by SebastianOpriel** [comment]
@richardtreier is this still an open issue?

**Comment by SebastianOpriel** [comment]
If necessary, please open it again.
