### ISSUE TITLE
Consuming Contract Agreements contain no Asset Information

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-ce#336]
# Bug

## Description

Right now we have no asset properties for consuming contract agreements in our Contract Agreement Endpoint.

The Core EDC team has said that this is not a bug and that they won't support us persisting any asset information during Contract Negotiation. 

The data model still supports it, and currently does the right thing on the consumer side. This, however, is considered a bug by the core EDC team and might get removed in the near future.

We'd want to save both providing and consuming Contract Agreement's Asset information in the Contract Negotiation's persisted Contract Offer List.

## Why Is the Feature Desired?

Our UI shows Asset Names in favor of Asset IDs. Asset properties are very central to the EDC data exchange, so we really need the information in the moment we try to consume data.

## Solution Proposal and Work Breakdown

- [ ] Implement an extension, that intercepts the right events at the right time, to then execute a request, to reliably (> 90%) fetch the asset properties, no matter how.
- [ ] We want to fetch the asset information at the right time. The Contract Offer might disappear already mid-negotiation if some n-times-consumable policies are in place.

**Comment by SebastianOpriel** [comment]
Duplicate, close in favor of https://github.com/sovity/edc-ce/issues/427
