### ISSUE TITLE
Make data consumer visible to data provider on Authority Portal

### ISSUE THREAD

**Issue by AbdullahMuk** [sovity/edc-ce#604]
# Feature Request

## Description

As a data provider who made data offers visible in the MDS, I want to see details about the consumers of my data offers, so that I can build on this transparency to refine my data offerings in the DS.
In the future as a MDS participant I, want to be able to push or pull data to/from other participants. Therefore I need to be able to contact these participants via Email.

Insights from SO's email
> Look-up at the portal (provider must know who the consumer is and possibly receive contact details)

## Which Areas Would Be Affected?

- edc-extensions
- authority portal

## Why Is the Feature Desired?

To achieve compatability with Mobilithek. This feature is a precondition to transfer data via pushing or pulling.

## How does this tie into the current product?

_Describe whether this request is related to an existing workflow, feature, or otherwise something in the product today. Or, does this open us up to new innovative ideas?_

## Stakeholders
- MDS
- @jkbquabeck 
- @SebastianOpriel 
- @sebk46 

## Solution Proposal and Work Breakdown

This is a large task as we need a Software Architecture breakthrough: Custom DSP Messages in EDC 0.

### Architecture

- Right now the AP has no way to talk to connectors.
- Since the only unit we have that talks to connectors alot, I'd propose the broker as also a metadata broker for connector usage.
- Since this is new information the connector would have to provide, we need custom DSP Messages. For that we need a breakthrough.

```[tasklist]
### Prerequisites
- [ ] Required Architecture Decision: What about security, what is sensitive information?
- [ ] Required Architecture Decision: Do we protect Connector self-information by having the Broker have a special identity in it's token (custom claim).
- [ ] Required Architecture Milestone: Custom (secure) DSP Message Achieved (EDC-Extensions + Broker Server)
```

```[tasklist]
### EDC Extensions / EDC Deployments
- [ ] New CE MDS Extension: Connector Self-Description, Providing Contract Information (counts, maybe transfer counts)
- [ ] EDC Deployments: MDS Variant adjustment (small task)
```

```[tasklist]
### Broker Server
- [ ] Scrape + Track Connector Self-Information on update. This needs to be fault-tolerant for custom MDS Connectors
- [ ] New API endpoints for the AP to query this data
- [ ] Collect Deployment Migration notes for the Operator regarding the broker IAM / DAT Claim
```

```[tasklist]
### Authority Portal
- [ ] Consume Connector Information from the Broker (can be in-memory)
- [ ] With an amazing data basis per connector with "other connected connectors + contracts + transfer amounts (maybe last 30d, etc.)" we can add this to multiple pages in the AP. This needs to be materialized. I suggest we add this information on the dashboard aggregated and per connector detailed / individually, meaning **two pages**
- [ ] Add the API for the two pages.
- [ ] Implement the API for the two pages.
- [ ] Add the information to the UI for the two pages.
```

**Comment by richardtreier** [comment]
Notes regarding estimation:
![grafik](https://github.com/sovity/edc-extensions/assets/30114507/452adb01-304e-420b-bb0b-7fda03771f97)

**Comment by jkbquabeck** [comment]
@richardtreier "New CE MDS Extension: Connector Self-Description, Providing Contract Information" Alignment with Authority Portal needed. A substitution for the Connector SD was supposed to be covered by Authority Portal.

**Comment by SebastianOpriel** [comment]
This feature does not make much sense as EDCs provide this information properly, thus closing
