### ISSUE TITLE
Breakthrough: Include E2E Tests from the EE in the CE

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-ce#623]
# Feature Request

## Description

There is https://docs.github.com/en/actions/creating-actions/sharing-actions-and-workflows-from-your-private-repository, which we could use to run private actions from the E2E repository. Either that or we find some external way to run tests and note the result in GH actions.

```[tasklist]
### Tasks
- [ ] Run E2E Tests in CI of CE with a limit to CE tests only
```

**Comment by SebastianOpriel** [comment]
What could help here? OS KC DAPS and integrating the image in pipelines/E2E tests?

**Comment by SebastianOpriel** [comment]
@richardtreier any update here?

**Comment by richardtreier** [comment]
out of date

**Comment by richardtreier** [comment]
achieved with v11
