### ISSUE TITLE
Validation of the logging house extension

### ISSUE THREAD

**Issue by jkbquabeck** [sovity/edc-ce#856]
--------------------MDS format for quick high level inspection---------------

https://github.com/Mobility-Data-Space/MDS-Project/issues/63

# Background

## Problem statement
According to legal requirements all transactions in our data space shall be logged. It means the logging house extension (LHE) which is already part of our EDC shall be always be activated and properly configured.

## Customer perspective
The participant shall have possibility Quick and easy to check whether the LHE is activated or not.

## Business value
Without this feature the data space has no possibility follow the federal antitrust act.

# Proposed solution

## Description of the feature
On launch the connector should check whether the LHE is properly configured. If the LHE is not properly configured, negotiations and transactions shall be diskaled. The participant shall be informed via UI that the connector is not configured properly.    

## Dependencies 
Logging House Extension, Logging House

## Suggested visual realization
TBD

# Challenges
TBD

# User stories
As Data Space Authority I want to be sure that all connectors in my data space use the logging house for logging.

As Participant I want to be informed via UI if my connector is disabled due to wrong LHE configuration.

# Outlook
Next step would be to ping the Logging House and to receive the approproate answer. This feature should be implemented on the LH side too.

**Comment by SebastianOpriel** [comment]
See https://github.com/sovity/edc-ui/issues/677 for frontend details
