### ISSUE TITLE
Implement a Kafka Data Plane

### ISSUE THREAD

**Issue by jkbquabeck** [sovity/edc-ce#860]
# Feature Request

----------MDS format for quick inspection------------
https://github.com/Mobility-Data-Space/MDS-Project/issues/62

# Background

## Problem statement
The crucial requirement in the mobility world is to avoid time delays by the traffic message transmission. Therefore streaming frameworks such as Kafka are already in use. Currently there is no possibility to use Kafka in our data space.

## Customer perspective
The perefect solution from the customer perspective would be: to combine the data space approach with available Kafka data source / data sinc.

## Business value
This is the crucial feature for the DFRS use case.

# Proposed solution

## Description of the feature
Kafka data plane shall be implemented.

## Dependencies 
TBD

## Glossary 
[Apache Kafka](https://de.wikipedia.org/wiki/Apache_Kafka)

## Suggested visual realization
_please add screenshots of the proposed visual realization_

# Challenges
_please mention possible challenges with the proposed feature_

# User stories
_please list all relevant user stories_

# Outlook
_please provide an outlook how this feature ties into future developments_

**Comment by SebastianOpriel** [comment]
@AbdullahMuk closing it for the moment, as there is no real demand yet

**Comment by SebastianOpriel** [comment]
https://github.com/Mobility-Data-Space/mds-edc/pull/232
